version: '3.1'
services:
  web:
    image: andreluizs/nginx
    container_name: nginx
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    volumes:
    - ./data/nginx/logs:/var/log/nginx/
    - ./src/:/usr/share/nginx/html/
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  php:
    image: andreluizs/php:7-fpm
    container_name: php
    build:
        context: .
        dockerfile: build/php/Dockerfile
    volumes:
      - ./src/:/usr/share/nginx/html/
  
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - ${PHP_MY_ADMIN_PORT}:80